/**
 * This file was auto-generated by openapi-typescript.
 * Do not make direct changes to the file.
 */

export interface paths {
    "/api/v1/health": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Health Check */
        get: operations["health_check_api_v1_health_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/auth/profile": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Create My Profile
         * @description Called once by the client right after Supabase Auth sign-up, to
         *     tell MomCare what role this newly-authenticated identity has. There is
         *     no server-guessed default role - see auth_service.create_profile.
         */
        post: operations["create_my_profile_api_v1_auth_profile_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/auth/me": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Read My Profile */
        get: operations["read_my_profile_api_v1_auth_me_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/iot/bands/{band_id}/pair": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Pair Band */
        post: operations["pair_band_api_v1_iot_bands__band_id__pair_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/iot/bands/{band_id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Get Band */
        get: operations["get_band_api_v1_iot_bands__band_id__get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/iot/vitals": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Ingest Vitals
         * @description Accepts one or more readings per call so a band that buffered
         *     locally during a connectivity gap can batch-upload them all on
         *     reconnect. Each reading is checked against alert thresholds as it's
         *     saved, so a stale batch still triggers alerts retroactively.
         */
        post: operations["ingest_vitals_api_v1_iot_vitals_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/iot/patients/{patient_id}/vitals": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** List Vitals */
        get: operations["list_vitals_api_v1_iot_patients__patient_id__vitals_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/iot/patients/{patient_id}/vitals/latest": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Latest Vitals */
        get: operations["latest_vitals_api_v1_iot_patients__patient_id__vitals_latest_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/alerts": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * List Alerts
         * @description Alert History (scope doc, module x) — backs both the doctor's
         *     Alert History page and the NGO's live emergency feed.
         */
        get: operations["list_alerts_api_v1_alerts_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/alerts/{alert_id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Get Alert */
        get: operations["get_alert_api_v1_alerts__alert_id__get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/alerts/{alert_id}/acknowledge": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Acknowledge Alert
         * @description Acknowledgment Tracking (scope doc, module x): records which
         *     stakeholder responded *first*. Later acknowledgements are rejected
         *     rather than overwriting, so the response-time audit stays honest.
         */
        post: operations["acknowledge_alert_api_v1_alerts__alert_id__acknowledge_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/alerts/{alert_id}/resolve": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Resolve Alert */
        post: operations["resolve_alert_api_v1_alerts__alert_id__resolve_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/ngos": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** List Ngos */
        get: operations["list_ngos_api_v1_ngos_get"];
        put?: never;
        /**
         * Register Ngo
         * @description Organization Credentialing (scope doc, module viii). Starts in
         *     PENDING — an NGO is invisible to the triage system until an admin
         *     approves it.
         */
        post: operations["register_ngo_api_v1_ngos_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/ngos/{ngo_id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Get Ngo */
        get: operations["get_ngo_api_v1_ngos__ngo_id__get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/ngos/{ngo_id}/resources": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        /**
         * Update Resources
         * @description Resource Inventory Logging (scope doc, module viii) — ambulances,
         *     nurses, field workers available for emergency dispatch.
         */
        patch: operations["update_resources_api_v1_ngos__ngo_id__resources_patch"];
        trace?: never;
    };
    "/api/v1/ngos/{ngo_id}/review": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Review Ngo
         * @description Admin Approval Workflow (scope doc, module viii). Approving an NGO
         *     puts it live in the triage system, so a decided application can't be
         *     silently flipped back to pending — it must be re-reviewed explicitly.
         */
        post: operations["review_ngo_api_v1_ngos__ngo_id__review_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/patients": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Create Patient
         * @description Create a new patient end-to-end, including Supabase Auth identity.
         */
        post: operations["create_patient_api_v1_patients_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
}
export type webhooks = Record<string, never>;
export interface components {
    schemas: {
        /** AlertAcknowledgeIn */
        AlertAcknowledgeIn: {
            /**
             * User Id
             * Format: uuid
             */
            user_id: string;
        };
        /** AlertOut */
        AlertOut: {
            /**
             * Id
             * Format: uuid
             */
            id: string;
            /**
             * Patient Id
             * Format: uuid
             */
            patient_id: string;
            /** Vital Reading Id */
            vital_reading_id: string | null;
            /** Alert Type */
            alert_type: string;
            /** Reading Summary */
            reading_summary: string;
            severity: components["schemas"]["AlertSeverity"];
            status: components["schemas"]["AlertStatus"];
            /** Channels Notified */
            channels_notified: string[];
            /**
             * Triggered At
             * Format: date-time
             */
            triggered_at: string;
            /** Acknowledged By User Id */
            acknowledged_by_user_id: string | null;
            /** Acknowledged At */
            acknowledged_at: string | null;
            /** Resolved At */
            resolved_at: string | null;
        };
        /** AlertResolveIn */
        AlertResolveIn: {
            /**
             * User Id
             * Format: uuid
             */
            user_id: string;
        };
        /**
         * AlertSeverity
         * @enum {string}
         */
        AlertSeverity: "urgent" | "critical";
        /**
         * AlertStatus
         * @enum {string}
         */
        AlertStatus: "pending" | "acknowledged" | "resolved";
        /**
         * BandStatus
         * @enum {string}
         */
        BandStatus: "available" | "assigned" | "faulty" | "retired";
        /**
         * ConnectivityStatus
         * @enum {string}
         */
        ConnectivityStatus: "strong" | "weak" | "offline";
        /** HTTPValidationError */
        HTTPValidationError: {
            /** Detail */
            detail?: components["schemas"]["ValidationError"][];
        };
        /** HealthBandOut */
        HealthBandOut: {
            /**
             * Id
             * Format: uuid
             */
            id: string;
            /** Serial Number */
            serial_number: string;
            /** Patient Id */
            patient_id: string | null;
            /** Ngo Id */
            ngo_id: string | null;
            status: components["schemas"]["BandStatus"];
            /** Battery Level */
            battery_level: number | null;
            connectivity: components["schemas"]["ConnectivityStatus"];
            /** Last Sync At */
            last_sync_at: string | null;
            /** Assigned At */
            assigned_at: string | null;
        };
        /** HealthBandPairIn */
        HealthBandPairIn: {
            /**
             * Patient Id
             * Format: uuid
             */
            patient_id: string;
        };
        /** NGOOut */
        NGOOut: {
            /**
             * Id
             * Format: uuid
             */
            id: string;
            /** Coordinator User Id */
            coordinator_user_id: string | null;
            /** Legal Name */
            legal_name: string;
            /** Registration Number */
            registration_number: string;
            /** Date Of Incorporation */
            date_of_incorporation: string | null;
            /** Service Area */
            service_area: string | null;
            /** Available Ambulances */
            available_ambulances: number;
            /** Qualified Nurses */
            qualified_nurses: number;
            /** Field Health Workers */
            field_health_workers: number;
            /** Registration Certificate Path */
            registration_certificate_path: string | null;
            /** Operational License Path */
            operational_license_path: string | null;
            status: components["schemas"]["NGOStatus"];
        };
        /** NGORegisterIn */
        NGORegisterIn: {
            /** Legal Name */
            legal_name: string;
            /** Registration Number */
            registration_number: string;
            /** Date Of Incorporation */
            date_of_incorporation?: string | null;
            /** Service Area */
            service_area?: string | null;
            /**
             * Available Ambulances
             * @default 0
             */
            available_ambulances: number;
            /**
             * Qualified Nurses
             * @default 0
             */
            qualified_nurses: number;
            /**
             * Field Health Workers
             * @default 0
             */
            field_health_workers: number;
            /** Coordinator User Id */
            coordinator_user_id?: string | null;
        };
        /** NGOResourcesIn */
        NGOResourcesIn: {
            /** Available Ambulances */
            available_ambulances?: number | null;
            /** Qualified Nurses */
            qualified_nurses?: number | null;
            /** Field Health Workers */
            field_health_workers?: number | null;
            /** Service Area */
            service_area?: string | null;
        };
        /**
         * NGOReviewIn
         * @description Admin Approval Workflow (scope doc, module viii).
         */
        NGOReviewIn: {
            status: components["schemas"]["NGOStatus"];
            /** Note */
            note?: string | null;
        };
        /**
         * NGOStatus
         * @description Admin Approval Workflow (scope doc, module viii) — an NGO only
         *     appears in the triage system once APPROVED.
         * @enum {string}
         */
        NGOStatus: "pending" | "under_review" | "approved" | "rejected";
        /** PatientCreate */
        PatientCreate: {
            /**
             * Email
             * Format: email
             */
            email: string;
            /** Password */
            password: string;
            /** Phone Number */
            phone_number?: string | null;
            /** Full Name */
            full_name: string;
            /** Age */
            age?: number | null;
            /** City */
            city?: string | null;
            /** Blood Group */
            blood_group?: string | null;
            /** Bmi */
            bmi?: number | null;
            /** Gestational Week */
            gestational_week?: number | null;
            /** Due Date */
            due_date?: string | null;
            /**
             * Previous C Section
             * @default false
             */
            previous_c_section: boolean;
            /** Conditions */
            conditions?: string[];
            /** Address1 */
            address1?: string | null;
            /** Address2 */
            address2?: string | null;
            /** State */
            state?: string | null;
            /** Postal Code */
            postal_code?: string | null;
            /** Provider Name */
            provider_name?: string | null;
            /** Secondary Provider */
            secondary_provider?: string | null;
            /** Nurse Name */
            nurse_name?: string | null;
            /** Rpm Diagnosis */
            rpm_diagnosis?: string | null;
            /** Rpm Consents */
            rpm_consents?: Record<string, never> | null;
            /** Glucose Min */
            glucose_min?: number | null;
            /** Glucose Max */
            glucose_max?: number | null;
            /** Sys Min */
            sys_min?: number | null;
            /** Sys Max */
            sys_max?: number | null;
            /** Dia Min */
            dia_min?: number | null;
            /** Dia Max */
            dia_max?: number | null;
            /** Hr Min */
            hr_min?: number | null;
            /** Hr Max */
            hr_max?: number | null;
        };
        /** PatientOut */
        PatientOut: {
            /**
             * Id
             * Format: uuid
             */
            id: string;
            /**
             * User Id
             * Format: uuid
             */
            user_id: string;
            /** Doctor Id */
            doctor_id?: string | null;
            /** Ngo Id */
            ngo_id?: string | null;
        };
        /** ProfileCreateIn */
        ProfileCreateIn: {
            /** Full Name */
            full_name: string;
            role: components["schemas"]["UserRole"];
            /** Phone Number */
            phone_number?: string | null;
        };
        /** ProfileOut */
        ProfileOut: {
            /**
             * Id
             * Format: uuid
             */
            id: string;
            /** Email */
            email: string | null;
            /** Full Name */
            full_name: string;
            role: components["schemas"]["UserRole"];
            /** Phone Number */
            phone_number: string | null;
            /** Is Active */
            is_active: boolean;
        };
        /**
         * UserRole
         * @enum {string}
         */
        UserRole: "mother" | "doctor" | "ngo_coordinator" | "admin";
        /** ValidationError */
        ValidationError: {
            /** Location */
            loc: (string | number)[];
            /** Message */
            msg: string;
            /** Error Type */
            type: string;
        };
        /**
         * VitalReadingBatchIn
         * @description A band buffers locally during connectivity gaps and batch-uploads
         *     on reconnect (scope doc, System Limitations), so ingestion always
         *     accepts a list — a live stream just sends lists of length 1.
         */
        VitalReadingBatchIn: {
            /**
             * Patient Id
             * Format: uuid
             */
            patient_id: string;
            /** Readings */
            readings: components["schemas"]["VitalReadingIn"][];
        };
        /** VitalReadingIn */
        VitalReadingIn: {
            /** Band Id */
            band_id?: string | null;
            /** Systolic Bp */
            systolic_bp?: number | null;
            /** Diastolic Bp */
            diastolic_bp?: number | null;
            /** Heart Rate */
            heart_rate?: number | null;
            /** Temperature */
            temperature?: number | null;
            /** Spo2 */
            spo2?: number | null;
            /** Activity Level */
            activity_level?: string | null;
            /** Sleep Quality */
            sleep_quality?: string | null;
            /**
             * Recorded At
             * Format: date-time
             */
            recorded_at: string;
        };
        /** VitalReadingOut */
        VitalReadingOut: {
            /**
             * Id
             * Format: uuid
             */
            id: string;
            /**
             * Patient Id
             * Format: uuid
             */
            patient_id: string;
            /** Band Id */
            band_id: string | null;
            /** Systolic Bp */
            systolic_bp: number | null;
            /** Diastolic Bp */
            diastolic_bp: number | null;
            /** Heart Rate */
            heart_rate: number | null;
            /** Temperature */
            temperature: number | null;
            /** Spo2 */
            spo2: number | null;
            /** Activity Level */
            activity_level: string | null;
            /** Sleep Quality */
            sleep_quality: string | null;
            /**
             * Recorded At
             * Format: date-time
             */
            recorded_at: string;
            /**
             * Synced At
             * Format: date-time
             */
            synced_at: string;
        };
    };
    responses: never;
    parameters: never;
    requestBodies: never;
    headers: never;
    pathItems: never;
}
export type $defs = Record<string, never>;
export interface operations {
    health_check_api_v1_health_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        [key: string]: string;
                    };
                };
            };
        };
    };
    create_my_profile_api_v1_auth_profile_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["ProfileCreateIn"];
            };
        };
        responses: {
            /** @description Successful Response */
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ProfileOut"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    read_my_profile_api_v1_auth_me_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ProfileOut"];
                };
            };
        };
    };
    pair_band_api_v1_iot_bands__band_id__pair_post: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                band_id: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["HealthBandPairIn"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HealthBandOut"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    get_band_api_v1_iot_bands__band_id__get: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                band_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HealthBandOut"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    ingest_vitals_api_v1_iot_vitals_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["VitalReadingBatchIn"];
            };
        };
        responses: {
            /** @description Successful Response */
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["VitalReadingOut"][];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    list_vitals_api_v1_iot_patients__patient_id__vitals_get: {
        parameters: {
            query?: {
                limit?: number;
            };
            header?: never;
            path: {
                patient_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["VitalReadingOut"][];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    latest_vitals_api_v1_iot_patients__patient_id__vitals_latest_get: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                patient_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["VitalReadingOut"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    list_alerts_api_v1_alerts_get: {
        parameters: {
            query?: {
                patient_id?: string | null;
                alert_status?: components["schemas"]["AlertStatus"] | null;
                limit?: number;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["AlertOut"][];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    get_alert_api_v1_alerts__alert_id__get: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                alert_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["AlertOut"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    acknowledge_alert_api_v1_alerts__alert_id__acknowledge_post: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                alert_id: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["AlertAcknowledgeIn"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["AlertOut"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    resolve_alert_api_v1_alerts__alert_id__resolve_post: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                alert_id: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["AlertResolveIn"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["AlertOut"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    list_ngos_api_v1_ngos_get: {
        parameters: {
            query?: {
                ngo_status?: components["schemas"]["NGOStatus"] | null;
                service_area?: string | null;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["NGOOut"][];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    register_ngo_api_v1_ngos_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["NGORegisterIn"];
            };
        };
        responses: {
            /** @description Successful Response */
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["NGOOut"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    get_ngo_api_v1_ngos__ngo_id__get: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                ngo_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["NGOOut"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    update_resources_api_v1_ngos__ngo_id__resources_patch: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                ngo_id: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["NGOResourcesIn"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["NGOOut"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    review_ngo_api_v1_ngos__ngo_id__review_post: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                ngo_id: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["NGOReviewIn"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["NGOOut"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    create_patient_api_v1_patients_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["PatientCreate"];
            };
        };
        responses: {
            /** @description Successful Response */
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["PatientOut"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
}
