import { AlertTriangle, ExternalLink } from "lucide-react";

import { safeSourceLinks } from "../carePlanLogic";
import type { SourceBasis, SourceLink } from "../types";

/**
 * Where a plan's advice came from — the part of the guide that matters most.
 *
 * - web_search: the official pages the AI used, as links. Never hidden.
 * - ai_only: no official guidance was found; the "generated by AI" notice is
 *   shown prominently and there are no links.
 * - baseline: the AI failed and a fixed generic plan is shown; its source line
 *   is shown and staff should review it.
 *
 * Whatever the basis, the sources are never presented as a guarantee: nobody
 * has checked that the advice follows them.
 */
export function SourcesBlock({
  basis,
  sources,
  sourceLinks,
  notice,
}: {
  basis: SourceBasis;
  sources: string[];
  sourceLinks: SourceLink[];
  notice: string | null;
}) {
  const links = safeSourceLinks(sourceLinks);

  return (
    <div style={{ marginTop: 12 }}>
      {basis === "ai_only" && (
        <p className="mc-alert mc-alert-notice" role="note">
          <AlertTriangle size={14} strokeWidth={2} aria-hidden />
          {notice ??
            "This plan was generated by AI. Please follow what your care team tells you."}
        </p>
      )}

      {basis === "baseline" && (
        <p className="mc-alert mc-alert-notice" role="note">
          <AlertTriangle size={14} strokeWidth={2} aria-hidden />
          {sources[0] ?? "MomCare generic safe baseline plan."} Staff should
          review it.
        </p>
      )}

      {basis === "web_search" && links.length > 0 && (
        <div>
          <div className="mc-card-sub" style={{ fontWeight: 600 }}>
            Sources
          </div>
          <ul
            style={{
              listStyle: "none",
              margin: "4px 0 0",
              padding: 0,
              display: "flex",
              flexDirection: "column",
              gap: 3,
            }}
          >
            {links.map((link) => (
              <li key={link.url}>
                <a
                  href={link.url}
                  target="_blank"
                  rel="noopener noreferrer"
                  className="mc-link"
                  style={{
                    display: "inline-flex",
                    alignItems: "center",
                    gap: 5,
                    fontSize: 12.5,
                  }}
                >
                  {link.title || link.host}
                  <span style={{ color: "var(--c-faint)" }}>{link.host}</span>
                  <ExternalLink size={11} strokeWidth={2} aria-hidden />
                </a>
              </li>
            ))}
          </ul>
        </div>
      )}

      <p className="mc-hint" style={{ marginTop: 6 }}>
        These are the pages the AI used. Nobody has checked that the advice
        follows them.
      </p>
    </div>
  );
}
